version: 2
jobs:
  build:
    docker:
      - image: golang:1.11-stretch@sha256:937c594413e17071786b7be003bfec95854cebb96d8f387739a6ee04b0b0dc70
    working_directory: /go/src/github.com/pagerinc/terraform-provider-aptible

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - run: make
